export const portfolioData = {
  personal: {
    name: "Huma Mohsin",
    title: "AI-Assisted Full-Stack Developer",
    location: "Karachi, Pakistan",
    linkedin: "https://www.linkedin.com/in/huma-mohsin-0b35382b5/",
    image: "/profile.jpg",
  },
  summary: `Junior Frontend/Full-Stack Developer skilled in building modern, responsive, and AI-powered web applications using Next.js, React, TypeScript, Tailwind CSS, and AI-native workflows. Experienced in building interactive, AI-powered applications, including mobile crime prevention systems (Sindh Police DIGP IT task) and AI-powered productivity apps. Strong foundation in API integration and AI-assisted automation.`,
  objective: `To contribute my frontend and AI-assisted development skills to a dynamic organization, build innovative digital solutions, and continue growing in modern web technologies.`,
  experience: [
    {
      title: "SMART TRACE - AI-Based Mobile Snatching Prevention & Recovery System",
      role: "Lead Full-Stack Architect (Solo Project)",
      agency: "Sindh Police (DIGP IT Office), Karachi",
      points: [
        "Selected to architect a Proof of Concept (PoC) for the DIG Office to modernize mobile theft prevention and recovery workflows.",
        "Engineered a secure system featuring CNIC-based registration, IMEI tracking, and shopkeeper monitoring modules.",
        "Designed a high-performance Admin Dashboard with real-time complaint tracking and crime heatmaps using Next.js 15.",
        "Developed an analytics layer for pattern recognition and predictive alerts to assist law enforcement.",
        "Spearheaded Claude CLI-driven architecture for rapid prototyping and technical documentation.",
      ],
    },
    {
      title: "AI-Native Full-Stack Developer",
      role: "Developer",
      points: [
        "Architected and deployed scalable web applications using Next.js 15, TypeScript, and Tailwind CSS.",
        "Implemented component-based architecture, dynamic routing, and React Server Components.",
        "Integrated AI-native workflows (Claude CLI & SpecKit) for rapid prototyping.",
        "Specialized in converting complex Figma designs into pixel-perfect user interfaces.",
        "Utilized advanced React Hooks and state management for seamless real-time updates.",
      ],
    },
  ],
  projects: [
    {
      title: "AI-Native Textbook Project",
      url: "https://humanoidrobotbook.vercel.app/",
      description: "AI-native documentation platform with RAG-based chatbot for Physical AI and Humanoid Robotics content.",
      tech: ["Next.js", "RAG", "AI", "TypeScript"],
    },
    {
      title: "AI-Powered Cloud-Native To-Do App",
      url: "https://cloud-native-ai-todo.vercel.app/",
      description: "Cloud-native to-do application with intelligent task handling and responsive UI.",
      tech: ["Next.js", "Cloud", "AI", "Full-Stack"],
    },
    {
      title: "AI Chat To-Do App (Phase 3)",
      url: "https://cloud-native-ai-todo-phase3-ai-chat.vercel.app/",
      description: "Enhanced app with AI-powered RAG chatbot for conversational task management.",
      tech: ["RAG", "AI Chat", "Next.js", "TypeScript"],
    },
    {
      title: "Dynamic Blog Platform",
      url: "https://milestone-3-completion-dynamic-blog-with-comment-section.vercel.app/",
      description: "Dynamic blog with multi-post support, comments, and category-based routing.",
      tech: ["Next.js", "Dynamic Routing", "React"],
    },
    {
      title: "E-Commerce Website",
      url: "https://day4-ecommerrce-website-nike-final-j95y.vercel.app/",
      description: "Responsive e-commerce frontend with product listings, filters, and detailed views.",
      tech: ["Next.js", "E-Commerce", "Tailwind CSS"],
    },
    {
      title: "Portfolio Website",
      url: "https://design-and-develop-a-personal-portfolio-website-with-custom-css.vercel.app/",
      description: "Professional portfolio showcasing projects with optimized layout and responsiveness.",
      tech: ["CSS", "Portfolio", "Responsive"],
    },
    {
      title: "Dynamic Resume Builder",
      url: "https://hackathon-milestone5-five.vercel.app/",
      description: "Interactive resume builder with real-time editing, PDF export, and shareable links.",
      tech: ["Next.js", "PDF", "Dynamic", "TypeScript"],
    },
  ],
  skills: {
    frontend: ["Next.js", "TypeScript", "HTML5", "CSS3", "Tailwind CSS", "ShadCN UI"],
    backend: ["Node.js", "Python", "FastAPI", "NestJS", "REST APIs", "JWT Auth"],
    database: ["PostgreSQL", "MongoDB", "Redis", "Sanity.io"],
    ai: ["Agentic AI Workflows", "SpecKit", "Claude CLI", "Generative AI", "Docusaurus"],
    tools: ["Git", "GitHub", "Figma", "Vercel", "npm"],
    soft: ["Communication", "Teamwork", "Problem-Solving", "Time Management", "Fast Learner", "Adaptable"],
  },
  education: [
    { qualification: "Certified Cloud Applied Generative AI", major: "Agentic AI And LLMs", year: "In Progress", institute: "Governor Sindh I.T Initiative" },
    { qualification: "BS", major: "Computer Science", year: "2015", institute: "Iqra University, Karachi" },
    { qualification: "Intermediate", major: "Pre-Engineering", year: "2005", institute: "Khursheed Govt. Girls College" },
    { qualification: "Matriculation", major: "Computer Science", year: "2003", institute: "Karachi Model School" },
  ],
  certifications: ["Volunteer Teacher — Roshni Public School (2012)"],
  achievements: [
    "Strategic AI Implementation (DIGP IT Sindh Police Task): Architected 'SMART TRACE' for mobile theft prevention.",
    "Integrated AI analytics layer for pattern recognition and anomaly detection.",
    "Deployed 10+ high-performance web applications using Next.js 15 and Tailwind CSS.",
    "Delivered key milestones for AI-Native Textbook Project using SpecKit AI and FastAPI.",
    "Architected Dynamic Resume Builder with real-time sync and automated PDF generation.",
    "Mastered App Router logic, global state management, and Microservices workflows.",
  ],
  strengths: [
    "Fast learner & highly adaptable",
    "Analytical and problem-solving mindset",
    "Effective communication skills",
    "Passionate about clean code & user-centric design",
  ],
  languages: ["English (Fluent)", "Urdu (Native)"],
  interests: ["Web Development", "AI Technologies", "UI/UX Design", "Tech Research", "Modern Frontend Frameworks"],
};
